sudo: false
services: mongodb

notifications:
  email: false

language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - jruby-19mode

gemfile:
  - Gemfile
  - gemfiles/carrierwave-0.9.gemfile
  - gemfiles/carrierwave-master.gemfile
  - gemfiles/mongoid-3.1.gemfile
  - gemfiles/mongoid-4.0.gemfile

matrix:
  allow_failures:
    - gemfile: gemfiles/carrierwave-master.gemfile
  fast_finish: true
